Create, publish and remove bargi images
CanalTP/mimirsbrunn pull request #462
Opened 2021-02-12 15:40 UTC by azime

Add job for publish bragi images on public registry

2021-02-12 20:59 UTC, crocme10 commented on Makefile
> +        TAGS=""; \
I don't understand the purpose of initializing the variable here, since you completely reassign it a couple of lines down

2021-02-12 21:11 UTC, crocme10 requested changes
These Makefile targets don't seem to 

1.  use any of the Makefile functionality: target dependencies. Since you're not building files, you might as well throw these lines in a shell script.
2.  if you want to keep them in a makefile, there is clearly an opportunity for reusing the same target with a variable (release / master)

2021-02-12 21:11 UTC, crocme10 commented on Makefile
> +        FIRST_ENV=$$(echo $(BUILD_ENV) | awk '{print $$1;}'); \
You define a variable here, but you don't seem to be using it after.

2021-02-12 21:11 UTC, crocme10 commented on Makefile
> +        TAGS=""; \
ditto

2021-02-12 21:11 UTC, crocme10 commented on Makefile
> +        FIRST_ENV=$$(echo $(BUILD_ENV) | awk '{print $$1;}'); \
ditto

2021-02-12 21:11 UTC, crocme10 commented on .github/workflows/create_publish_bragi_docker.yml
> +          push-bragi-image-${{ env.BRANCH_NAME }}
make push-....?

2021-02-12 21:12 UTC, crocme10 commented
oh, yes and it's 'bragi' ;-)

2021-02-13 23:24 UTC, crocme10 commented on Makefile
> +        docker build $(DOCKER_BUILD_ARGS) $$ARG_DEB $$ARG_RST $$TAGS -f docker/bragi/Dockerfile . ; \
If I read this correctly, the tags will be something like `navitia/bragi:master`.... so are you dropping all references to a version number?

2021-02-16 11:38 UTC, azime commented on Makefile
> +        docker build $(DOCKER_BUILD_ARGS) $$ARG_DEB $$ARG_RST $$TAGS -f docker/bragi/Dockerfile . ; \
For Dev, yes.
We are going to have that

2021-02-16 11:39 UTC, azime commented on .github/workflows/create_publish_bragi_docker.yml
> +          push-bragi-image-${{ env.BRANCH_NAME }}
make push-master or make push-release

2021-02-16 18:21 UTC, azime commented on Makefile
> +        FIRST_ENV=$$(echo $(BUILD_ENV) | awk '{print $$1;}'); \
ok

2021-02-16 18:21 UTC, azime commented on Makefile
> +        TAGS=""; \
ok

2021-02-16 18:21 UTC, azime commented on Makefile
> +        FIRST_ENV=$$(echo $(BUILD_ENV) | awk '{print $$1;}'); \
pk

2021-02-16 18:21 UTC, azime commented on Makefile
> +        TAGS=""; \
ok

2021-02-18 07:22 UTC, crocme10 requested changes
Since we can get the old Makefile thrgough git history, I think you should remove it all together. Also, there is an accompanying script '.make-release-support' which you can remove because you don't use it in your makefile

2021-02-18 07:22 UTC, crocme10 commented on .github/workflows/create_publish_bragi_docker.yml
> +          push-bragi-image-${{ env.BRANCH_NAME }}
I am saying aren't you missing a 'make' in front of 'push-bragi-image'?

2021-02-18 07:22 UTC, crocme10 commented on Makefile
> +dockerhub-login: ## Login Docker hub, DOCKERHUB_USER, DOCKERHUB_PWD, must be provided
In your comment you call it DOCKERHUB_PWD, and then you use DOCKERHUB_PASSWORD.

2021-02-18 07:22 UTC, crocme10 commented on Makefile
> +wipe-useless-images: ## Remove all useless images
Useless.... I assume you mean former images whose tag has been 'master' or 'release' has been overwriten?

2021-02-18 08:31 UTC, azime commented on .github/workflows/create_publish_bragi_docker.yml
> +          push-bragi-image-${{ env.BRANCH_NAME }}
:+1:

2021-02-19 08:55 UTC, crocme10 approved these changes

2021-02-24 15:56 UTC, benoit-bst approved these changes

2021-03-02 13:28 UTC, benoit-bst approved these changes

2021-03-02 13:35 UTC, merged