Add elasticsearch explain feature to bragi
CanalTP/mimirsbrunn pull request #604
Opened 2021-10-27 15:48 UTC by fatal69100

-> Review requested for the last 2 commits

Add elasticsearch explain endpoint to bragi (https://www.elastic.co/guide/en/elasticsearch/reference/7.14/search-explain.html)

2021-11-02 13:08 UTC, remi-dupre requested changes
:+1:

2021-11-02 13:08 UTC, remi-dupre commented on README.md
> -| staus              | `/status`  | None       |
This made me think that it would be a good idea to update the README to add `/autocomplete-explain` to the list of existing endpoint in previous section.

Also, this is a detail but this has broken the alignment of vertical lines (which is still syntactically ok, html rendering not broken) :smile:

2021-11-02 13:08 UTC, remi-dupre commented on libs/mimir2/src/adapters/primary/bragi/api.rs
> +    pub id: String,
Maybe this should be called `doc_id` to make it very clear that this is not homogeneous with other parameters which relate to the query?

What do you think? This may be a bad idea, I usually have bad taste when it comes to naming think.

2021-11-02 14:53 UTC, fatal69100 commented on README.md
> -| staus              | `/status`  | None       |
yes, btw I was searching something that could generate automatically documentation from API (such as swagger in Rust) because it will be easier to maintained documentation if it is generated from the code.

2021-11-02 14:57 UTC, fatal69100 commented on libs/mimir2/src/adapters/primary/bragi/api.rs
> +    pub id: String,
I think you are absolutely right for this one !! It's much more expressive

2021-11-02 16:51 UTC, fatal69100 commented
Can you review the last 2 commits with the serde default value ? I am unsure about the limit parameter for  the ReverseGeocoderQuery struct

2021-11-03 06:55 UTC, remi-dupre commented
> Can you review the last 2 commits with the serde default value please? I am unsure about the limit parameter for the `ReverseGeocoderQuery` struct

I think this is okay :+1:

2021-11-03 06:56 UTC, remi-dupre approved these changes

2021-11-03 08:24 UTC, merged