re-implement metric `bragi_elasticsearch_request_duration_seconds`
CanalTP/mimirsbrunn pull request #739
Opened 2022-03-23 11:07 UTC by remi-dupre

This was a metric that was computed for the ES2 branch and will be useful to debug were the time is spent during computation.

2022-03-23 13:09 UTC, woshilapin requested changes

2022-03-23 13:09 UTC, woshilapin commented on libs/mimir/src/adapters/primary/bragi/handlers.rs
> +use prometheus::{exponential_buckets, register_histogram_vec, HistogramVec};
This will cause problems since `promotheus` is an optional dependency. You can see the issue if you try to compile with the following command.

```
cargo check --package mimir --no-default-features
```

Maybe we can also try to add something in the CI to cover this kind of case?

2022-03-23 13:47 UTC, remi-dupre commented on libs/mimir/src/adapters/primary/bragi/handlers.rs
> +use prometheus::{exponential_buckets, register_histogram_vec, HistogramVec};
Oh thanks, I forgot about that :+1:

2022-03-25 08:26 UTC, remi-dupre commented on libs/mimir/src/adapters/primary/bragi/handlers.rs
> +use prometheus::{exponential_buckets, register_histogram_vec, HistogramVec};
That should be fixed now :wink:

2022-03-28 12:30 UTC, azime approved these changes

2022-03-28 13:41 UTC, woshilapin commented on libs/mimir/src/adapters/primary/bragi/handlers.rs
> +#[cfg(metrics)]
I don't believe this is correct. Did you try that metrics worked since you made this change? On my side, I tried to add the following to see if this syntax worked and had no compilation error.

```rust
#[cfg(metrics)]
std::compile_error("panic on metrics");
```

and nothing happened. I think you meant to write `#[cfg(feature = "metrics")]`.

2022-03-28 14:42 UTC, woshilapin approved these changes

2022-03-28 15:34 UTC, merged